server:
  port: 9999
#  servlet:
#    context-path: /sunshine

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/human_resource?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /jsp/
      suffix: .jsp

mybatis-plus:
  type-aliases-package: com.sunshine.management.entity
  mapper-locations: classpath:/mapper/**.xml
  size: 1
